services:
  # app:
  #   ...
  psql:
    image: postgres:latest
    container_name: just-ride-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riderize
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
